AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  voice-embedding

Resources:
  VoiceEmbeddingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      MemorySize: 2048
      Runtime: python3.13
      Handler: voice_embedding.lambda_handler
      CodeUri: src/voice_embedding/
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy
      Tracing: Active
      LoggingConfig:
        LogFormat: JSON
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: PowertoolsVoiceEmbedding
          POWERTOOLS_METRICS_NAMESPACE: Powertools
